name: Publish

on:
  workflow_dispatch:

jobs:
  publish:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        toolchain: [ stable ]
    runs-on: ${{ matrix.os }}
    steps:

      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: Set up Cache
        uses: Swatinem/rust-cache@v2

      - name: Install Cargo:semver
        run: cargo install cargo-semver-checks --locked

      - name: Run Cargo:semver
        run: cargo semver-checks check-release

      - name: Publish to crates.io
        run: cargo publish --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
